spring.application.name=demo

camel.crypto.secret-key=${APP_CRYPTO_KEY:MySecretKey12345}

server.port=8081
server.ssl.enabled=true

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=camelproxy
server.ssl.key-store-password=password123

camel.component.activemq.broker-url=tcp://localhost:61616
camel.component.activemq.username=${ACTIVEMQ_USER:admin}
camel.component.activemq.password=${ACTIVEMQ_PASSWORD:admin}

camel.component.activemq.use-pooled-connection=true
camel.component.activemq.max-concurrent-consumers=50